// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>HostMonitor</title><link href=\"static/style.css\" rel=\"stylesheet\"><script src=\"static/htmx.min.js\"></script></head><body class=\"font-sans bg-zinc-950 min-h-screen text-zinc-100\"><!-- Fixed Header --><header class=\"site-header\" role=\"banner\"><div class=\"header-inner\"><div class=\"header-logo\" aria-label=\"HostMonitor\"><svg class=\"logo-icon\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" aria-hidden=\"true\" focusable=\"false\"><rect x=\"2\" y=\"3\" width=\"20\" height=\"14\" rx=\"2\"></rect> <path d=\"M8 21h8M12 17v4\"></path> <path d=\"M6 8l3 3 2-2 3 4 2-3\"></path></svg> <span class=\"logo-text\">HostMonitor</span></div><div class=\"header-status\" role=\"status\" aria-live=\"polite\"><span class=\"status-dot\" aria-hidden=\"true\"></span> <span class=\"status-text\">Live</span> <span class=\"status-interval\">· updates every 10s</span></div></div></header><!-- Main content with top padding for fixed header --><main class=\"main-content\" id=\"main-content\"><div hx-get=\"/host\" hx-trigger=\"load, every 10s\" hx-swap=\"innerHTML\" aria-label=\"System information panel\"><div class=\"loading-state\" role=\"status\" aria-label=\"Loading system information\"><div class=\"loading-spinner\" aria-hidden=\"true\"></div><span>Loading system information…</span></div></div></main></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
